// Generated by scripts/x-import.mjs — do not edit by hand.
import type { Post } from "./posts";

export const POSTS: Post[] = [
  {
    "id": "2064710819875856883",
    "url": "https://x.com/AdityaKalsaria/status/2064710819875856883",
    "author": "AdityaKalsaria",
    "authorName": "Aditya kalsaria",
    "date": "2026-06-10T14:06:34.000Z",
    "text": "ahmmm ahmmm @koshmoney automatically handles adding bank details for you. Just paste it and voila.",
    "likes": 23,
    "video": true,
    "media": {
      "src": "/posts/2064710819875856883.webp",
      "width": 1600,
      "height": 900
    }
  },
  {
    "id": "2062563625894822023",
    "url": "https://x.com/AdityaKalsaria/status/2062563625894822023",
    "author": "AdityaKalsaria",
    "authorName": "Aditya kalsaria",
    "date": "2026-06-04T15:54:23.000Z",
    "text": "App Store screenshots designed for our Kosh App",
    "likes": 38,
    "video": true,
    "media": {
      "src": "/posts/2062563625894822023.webp",
      "width": 178900,
      "height": 102100
    }
  },
  {
    "id": "2060031160743542979",
    "url": "https://x.com/AdityaKalsaria/status/2060031160743542979",
    "author": "AdityaKalsaria",
    "authorName": "Aditya kalsaria",
    "date": "2026-05-28T16:11:16.000Z",
    "text": "New day new animation, infinite money glitch for @koshmoney Made in #cavalry",
    "likes": 21,
    "video": true,
    "media": {
      "src": "/posts/2060031160743542979.webp",
      "width": 900,
      "height": 1600
    }
  },
  {
    "id": "2059608565225320917",
    "url": "https://x.com/AdityaKalsaria/status/2059608565225320917",
    "author": "AdityaKalsaria",
    "authorName": "Aditya kalsaria",
    "date": "2026-05-27T12:12:02.000Z",
    "text": "Money in my DNA 🧬 made in @cavalry__app",
    "likes": 5,
    "video": true,
    "media": {
      "src": "/posts/2059608565225320917.webp",
      "width": 100,
      "height": 100
    }
  },
  {
    "id": "2057827133469446368",
    "url": "https://x.com/AdityaKalsaria/status/2057827133469446368",
    "author": "AdityaKalsaria",
    "authorName": "Aditya kalsaria",
    "date": "2026-05-22T14:13:15.000Z",
    "text": "Playing around in @cavalry__app is always fun!",
    "likes": 10,
    "video": true,
    "media": {
      "src": "/posts/2057827133469446368.webp",
      "width": 100,
      "height": 100
    }
  },
  {
    "id": "2056378181104656862",
    "url": "https://x.com/dalpattapaniya/status/2056378181104656862",
    "author": "dalpattapaniya",
    "authorName": "Dalpat / KOSH",
    "date": "2026-05-18T14:15:38.000Z",
    "text": "Virtual Accounts 🇺🇸 🇪🇺 🇬🇧 is live on @koshmoney app. - Receive payments from any freelancing platforms - Get paid from your clients - Fund your onchain trade accounts with USDC iOS: Android:",
    "likes": 33,
    "video": true,
    "media": {
      "src": "/posts/2056378181104656862.webp",
      "width": 1600,
      "height": 900
    }
  },
  {
    "id": "2051705622949986675",
    "url": "https://x.com/dalpattapaniya/status/2051705622949986675",
    "author": "dalpattapaniya",
    "authorName": "Dalpat / KOSH",
    "date": "2026-05-05T16:48:34.000Z",
    "text": "I’m working with @AdityaKalsaria, @sujalkalsaria, and @sumitXbravo on the KOSH onboarding flow. Onboarding is one of the most challenging parts of building an app like a neobank. We just made our first version live and are tracking every signup to make the experience smoother,",
    "likes": 45,
    "video": true,
    "media": {
      "src": "/posts/2051705622949986675.webp",
      "width": 1600,
      "height": 900
    }
  },
  {
    "id": "2046210586699350332",
    "url": "https://x.com/AdityaKalsaria/status/2046210586699350332",
    "author": "AdityaKalsaria",
    "authorName": "Aditya kalsaria",
    "date": "2026-04-20T12:53:15.000Z",
    "text": "Playing with forge dynamics in Cavalry",
    "likes": 14,
    "video": false,
    "media": {
      "src": "/posts/2046210586699350332.webp",
      "width": 2298,
      "height": 2452
    }
  },
  {
    "id": "2042592802463453634",
    "url": "https://x.com/AdityaKalsaria/status/2042592802463453634",
    "author": "AdityaKalsaria",
    "authorName": "Aditya kalsaria",
    "date": "2026-04-10T13:17:28.000Z",
    "text": "As a part of our animated icon library presenting Security Lock animated Icon, send your funds securely with @koshmoney 🔒🍀",
    "likes": 16,
    "video": true,
    "media": {
      "src": "/posts/2042592802463453634.webp",
      "width": 100,
      "height": 100
    }
  },
  {
    "id": "2042229850845721023",
    "url": "https://x.com/AdityaKalsaria/status/2042229850845721023",
    "author": "AdityaKalsaria",
    "authorName": "Aditya kalsaria",
    "date": "2026-04-09T13:15:13.000Z",
    "text": "Freshly cooked this cute Face ID Icon with our @koshmoney Multi-currencies pattern, this one is my personally favourite. More icons coming soon!😉",
    "likes": 37,
    "video": true,
    "media": {
      "src": "/posts/2042229850845721023.webp",
      "width": 100,
      "height": 100
    }
  },
  {
    "id": "2041485488046104743",
    "url": "https://x.com/AdityaKalsaria/status/2041485488046104743",
    "author": "AdityaKalsaria",
    "authorName": "Aditya kalsaria",
    "date": "2026-04-07T11:57:23.000Z",
    "text": "3D globe built with our @koshmoney multi-currencies pattern. 🌎💱 stay tuned for more!",
    "likes": 22,
    "video": true,
    "media": {
      "src": "/posts/2041485488046104743.webp",
      "width": 300,
      "height": 400
    }
  },
  {
    "id": "2041163121734365253",
    "url": "https://x.com/AdityaKalsaria/status/2041163121734365253",
    "author": "AdityaKalsaria",
    "authorName": "Aditya kalsaria",
    "date": "2026-04-06T14:36:25.000Z",
    "text": "We explored motion systems for our @koshmoney brand and marketing design. This multi-currency animation is fully custom-built using Cavalry for procedural pattern generation + After Effects for final polish. Designed to scale across products, not just a one-off visual. will",
    "likes": 36,
    "video": true,
    "media": {
      "src": "/posts/2041163121734365253.webp",
      "width": 100,
      "height": 100
    }
  },
  {
    "id": "2040431050867052634",
    "url": "https://x.com/AdityaKalsaria/status/2040431050867052634",
    "author": "AdityaKalsaria",
    "authorName": "Aditya kalsaria",
    "date": "2026-04-04T14:07:26.000Z",
    "text": "Zero prompt have been used while making this @koshmoney logo animation, more things are coming soon 😉😉😉 Will breakdown the process in next tweet how did we pulled up this ascii style animation with pure animation tool only🍀",
    "likes": 21,
    "video": true,
    "media": {
      "src": "/posts/2040431050867052634.webp",
      "width": 100,
      "height": 100
    }
  },
  {
    "id": "2035003872117457289",
    "url": "https://x.com/AdityaKalsaria/status/2035003872117457289",
    "author": "AdityaKalsaria",
    "authorName": "Aditya kalsaria",
    "date": "2026-03-20T14:41:46.000Z",
    "text": "Just got my hands on our @koshmoney TestFlight and its Smooth like butter 🧈 Comment KOSH, I'll share TestFlight link with you!",
    "likes": 32,
    "video": true,
    "media": {
      "src": "/posts/2035003872117457289.webp",
      "width": 172800,
      "height": 111700
    }
  },
  {
    "id": "2000879533965369653",
    "url": "https://x.com/koshmoney/status/2000879533965369653",
    "author": "koshmoney",
    "authorName": "KOSH",
    "date": "2025-12-16T10:43:50.000Z",
    "text": "2025 Solana Breakpoint was an Absolute Cinema @SolanaConf",
    "likes": 30,
    "video": true,
    "media": {
      "src": "/posts/2000879533965369653.webp",
      "width": 1600,
      "height": 900
    }
  },
  {
    "id": "1999776907605463065",
    "url": "https://x.com/AdityaKalsaria/status/1999776907605463065",
    "author": "AdityaKalsaria",
    "authorName": "Aditya kalsaria",
    "date": "2025-12-13T09:42:23.000Z",
    "text": "KOSH was all around the Breakpoint venue on day 2 💳 Did you catch us at @SolanaConf ?",
    "likes": 31,
    "video": true,
    "media": {
      "src": "/posts/1999776907605463065.webp",
      "width": 1600,
      "height": 900
    }
  },
  {
    "id": "1999367239297044480",
    "url": "https://x.com/AdityaKalsaria/status/1999367239297044480",
    "author": "AdityaKalsaria",
    "authorName": "Aditya kalsaria",
    "date": "2025-12-12T06:34:30.000Z",
    "text": "Day 1 of @SolanaConf was an absolute cinema 💜 Ready to rock with HUGE ANNOUNCEMENT toady!",
    "likes": 26,
    "video": true,
    "media": {
      "src": "/posts/1999367239297044480.webp",
      "width": 32000,
      "height": 17300
    }
  },
  {
    "id": "1971215897621823850",
    "url": "https://x.com/AdityaKalsaria/status/1971215897621823850",
    "author": "AdityaKalsaria",
    "authorName": "Aditya kalsaria",
    "date": "2025-09-25T14:11:08.000Z",
    "text": "What went wrong 🤯with our @koshmoney card launch?",
    "likes": 82,
    "video": true,
    "media": {
      "src": "/posts/1971215897621823850.webp",
      "width": 1600,
      "height": 900
    }
  }
];
