// Generated by scripts/figma-import.mjs — do not edit by hand.
// Empty until the importer has run; the site falls back to placeholders.
import type { Category } from "./work";

export const GENERATED: Category[] = [];
